language: php

sudo: true

php:
  - 7.0

before_install:
  # updates composer on travis
  - travis_retry composer self-update
  # clear composer cache, might speed up finding new tags
  - travis_retry composer clear-cache
  # include prestissimo which speeds up package download
  - composer global require hirak/prestissimo

install:
  # set the global github token, so connections won't be cancelled
  - composer config -g github-oauth.github.com $GITHUB_TOKEN

after_success:
  - bash <(curl -s https://codecov.io/bash)

after_failure:
  - cat /var/log/travis-queue.log
  
script:
  - phpunit --coverage-text --coverage-clover=coverage.clover
